### ISSUE TITLE
Nullpointer Exception in LcdSkin.redraw at PrismTextLayout.java:772

### ISSUE THREAD

**Issue by WolfgangFahl** [HanSolo/Medusa#126]
```
java.lang.NullPointerException
        at com.sun.javafx.text.PrismTextLayout.buildRuns(PrismTextLayout.java:772)
        at com.sun.javafx.text.PrismTextLayout.layout(PrismTextLayout.java:1021)
        at com.sun.javafx.text.PrismTextLayout.ensureLayout(PrismTextLayout.java:223)
        at com.sun.javafx.text.PrismTextLayout.getBounds(PrismTextLayout.java:246)
        at javafx.scene.text.Text.getLogicalBounds(Text.java:358)
        at javafx.scene.text.Text.impl_computeLayoutBounds(Text.java:1115)
        at javafx.scene.Node$12.computeBounds(Node.java:3223)
        at javafx.scene.Node$LazyBoundsProperty.get(Node.java:9306)
        at javafx.scene.Node$LazyBoundsProperty.get(Node.java:9276)
        at javafx.scene.Node.getLayoutBounds(Node.java:3238)
        at eu.hansolo.medusa.skins.LcdSkin.updateBackgroundText(LcdSkin.java:464)
        at eu.hansolo.medusa.skins.LcdSkin.redraw(LcdSkin.java:691)
        at eu.hansolo.medusa.skins.LcdSkin.handleEvents(LcdSkin.java:256)
        at eu.hansolo.medusa.skins.LcdSkin.lambda$new$0(LcdSkin.java:138)
        at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:136)
        at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
        at javafx.beans.property.DoublePropertyBase.fireValueChangedEvent(DoublePropertyBase.java:106)
        at javafx.beans.property.DoublePropertyBase.markInvalid(DoublePropertyBase.java:113)
        at javafx.beans.property.DoublePropertyBase.set(DoublePropertyBase.java:147)
        at eu.hansolo.medusa.Gauge$2.set(Gauge.java:481)
```

**Comment by HanSolo** [comment]
without a procedure to reproduce this bug, this description is useless.
