### ISSUE TITLE
Using sections or areas results in StackOverflowException

### ISSUE THREAD

**Issue by countfloyd** [HanSolo/Medusa#15]
Calling setAreas or setSections on a gauge results in:

```
Exception in thread "JavaFX Application Thread" java.lang.StackOverflowError
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at eu.hansolo.medusa.Gauge.fireUpdateEvent(Gauge.java:2313)
	at eu.hansolo.medusa.Gauge.setMajorTickSpace(Gauge.java:1881)
	at eu.hansolo.medusa.Gauge.calcAutoScale(Gauge.java:2100)
	at eu.hansolo.medusa.skins.QuarterSkin.handleEvents(QuarterSkin.java:354)
	at eu.hansolo.medusa.skins.QuarterSkin.lambda$registerListeners$91(QuarterSkin.java:294)
	at eu.hansolo.medusa.Gauge.lambda$fireUpdateEvent$1(Gauge.java:2313)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at eu.hansolo.medusa.Gauge.fireUpdateEvent(Gauge.java:2313)
	at eu.hansolo.medusa.Gauge.setMajorTickSpace(Gauge.java:1881)
	at eu.hansolo.medusa.Gauge.calcAutoScale(Gauge.java:2100)
	at eu.hansolo.medusa.skins.QuarterSkin.handleEvents(QuarterSkin.java:354)
	at eu.hansolo.medusa.skins.QuarterSkin.lambda$registerListeners$91(QuarterSkin.java:294)
	at eu.hansolo.medusa.Gauge.lambda$fireUpdateEvent$1(Gauge.java:2313)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at eu.hansolo.medusa.Gauge.fireUpdateEvent(Gauge.java:2313)
	at eu.hansolo.medusa.Gauge.setMajorTickSpace(Gauge.java:1881)
	at eu.hansolo.medusa.Gauge.calcAutoScale(Gauge.java:2100)
	at eu.hansolo.medusa.skins.QuarterSkin.handleEvents(QuarterSkin.java:354)
	at eu.hansolo.medusa.skins.QuarterSkin.lambda$registerListeners$91(QuarterSkin.java:294)
	at eu.hansolo.medusa.Gauge.lambda$fireUpdateEvent$1(Gauge.java:2313)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at eu.hansolo.medusa.Gauge.fireUpdateEvent(Gauge.java:2313)
	at eu.hansolo.medusa.Gauge.setMajorTickSpace(Gauge.java:1881)
	at eu.hansolo.medusa.Gauge.calcAutoScale(Gauge.java:2100)
```

**Comment by HanSolo** [comment]
Fixed with last commit
