### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by MichalHe** [HanSolo/Medusa#36]
```
Exception in thread "JavaFX Application Thread" java.lang.StackOverflowError
	at java.lang.StrictMath.floor(StrictMath.java:359)
	at java.lang.Math.floor(Math.java:442)
	at eu.hansolo.medusa.tools.Helper.calcNiceNumber(Helper.java:107)
	at eu.hansolo.medusa.Gauge.calcAutoScale(Gauge.java:4763)
	at eu.hansolo.medusa.skins.LinearSkin.handleEvents(LinearSkin.java:244)
	at eu.hansolo.medusa.skins.LinearSkin.lambda$registerListeners$2(LinearSkin.java:208)
	at eu.hansolo.medusa.Gauge.fireUpdateEvent(Gauge.java:5083)
	at eu.hansolo.medusa.Gauge.setMajorTickSpace(Gauge.java:4205)
	at eu.hansolo.medusa.Gauge.calcAutoScale(Gauge.java:4764)
	at eu.hansolo.medusa.skins.LinearSkin.handleEvents(LinearSkin.java:244)
	at eu.hansolo.medusa.skins.LinearSkin.lambda$registerListeners$2(LinearSkin.java:208)
	at eu.hansolo.medusa.Gauge.fireUpdateEvent(Gauge.java:5083)
	at eu.hansolo.medusa.Gauge.setMajorTickSpace(Gauge.java:4205)
	at eu.hansolo.medusa.Gauge.calcAutoScale(Gauge.java:4764)
	at eu.hansolo.medusa.skins.LinearSkin.handleEvents(LinearSkin.java:244)
	at eu.hansolo.medusa.skins.LinearSkin.lambda$registerListeners$2(LinearSkin.java:208)
	at eu.hansolo.medusa.Gauge.fireUpdateEvent(Gauge.java:5083)
	at eu.hansolo.medusa.Gauge.setMajorTickSpace(Gauge.java:4205)
	at eu.hansolo.medusa.Gauge.calcAutoScale(Gauge.java:4764)
	at eu.hansolo.medusa.skins.LinearSkin.handleEvents(LinearSkin.java:244)
	at eu.hansolo.medusa.skins.LinearSkin.lambda$registerListeners$2(LinearSkin.java:208)
	at eu.hansolo.medusa.Gauge.fireUpdateEvent(Gauge.java:5083)
	at eu.hansolo.medusa.Gauge.setMajorTickSpace(Gauge.java:4205)
	at eu.hansolo.medusa.Gauge.calcAutoScale(Gauge.java:4764)
	at eu.hansolo.medusa.skins.LinearSkin.handleEvents(LinearSkin.java:244)
	at eu.hansolo.medusa.skins.LinearSkin.lambda$registerListeners$2(LinearSkin.java:208)
	at eu.hansolo.medusa.Gauge.fireUpdateEvent(Gauge.java:5083)
	at eu.hansolo.medusa.Gauge.setMajorTickSpace(Gauge.java:4205)
	at eu.hansolo.medusa.Gauge.calcAutoScale(Gauge.java:4764)
```
is created by following code:
```
 setZeroButton.setOnMouseClicked(event -> {
            double max_value = gauge.getMaxValue() - gauge.getCurrentValue();
            double min_value = 0 - gauge.getCurrentValue();
            gauge.setMaxValue(max_value);
            gauge.setMinValue(min_value);
        });
```
Any ideas what am I doing wrong?

**Comment by HanSolo** [comment]
You try to change the min and max value of the gauge during runtime and when the autoScale property is switched on. The gauges are not designed to change the min and max values during runtime because a lot of calculations and drawings depend on that values. The calcAutoScale() method is always called when you change settings like minValue, maxValue, minorTickSpace, majorTickspace etc. And it sets the min- and maxValue to nice values which is a problem if you try to set them manually.
