### ISSUE TITLE
SceneBuilder throws exception when loading 5.9 jar file 

### ISSUE THREAD

**Issue by rterp** [HanSolo/Medusa#43]
I'm attempting to load the Medusa 5.9 jar file in SceneBuilder and am encountering the following error
when viewing the .jar analysis report.

```
Exception for: eu/hansolo/medusa/FGauge.class
java.io.IOException: java.lang.ExceptionInInitializerError
    at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.instantiateWithFXMLLoader(JarExplorer.java:111)
    at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.exploreEntry(JarExplorer.java:154)
    at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.explore(JarExplorer.java:67)
    at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.exploreAndUpdateLibrary(LibraryFolderWatcher.java:313)
    at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.runDiscovery(LibraryFolderWatcher.java:142)
    at com.oracle.javafx.scenebuilder.kit.library.user.LibraryFolderWatcher.run(LibraryFolderWatcher.java:94)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ExceptionInInitializerError
    at eu.hansolo.medusa.Gauge.<init>(Gauge.java:113)
    at eu.hansolo.medusa.Gauge.<init>(Gauge.java:379)
    at eu.hansolo.medusa.FGauge.<init>(FGauge.java:61)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at java.lang.Class.newInstance(Class.java:442)
    at sun.reflect.misc.ReflectUtil.newInstance(ReflectUtil.java:51)
    at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1009)
    at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:746)
    at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)
    at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2425)
    at com.oracle.javafx.scenebuilder.kit.library.util.JarExplorer.instantiateWithFXMLLoader(JarExplorer.java:107)
    ... 6 more
Caused by: java.lang.IllegalArgumentException: EventType "BTN_PRESSED"with parent "EVENT" already exists
    at javafx.event.EventType.register(EventType.java:186)
    at javafx.event.EventType.<init>(EventType.java:128)
    at eu.hansolo.medusa.Gauge$ButtonEvent.<clinit>(Gauge.java:5197)
    ... 21 more


```

**Comment by HanSolo** [comment]
There is an issue in SceneBuilder (https://bitbucket.org/gluon-oss/scenebuilder/issues/70/custom-components-disappear-from-custom) which might explain it but it doesn't seem to be an issue within Medusa. I saw that the exception only appears the first time you use the library, when I close SceneBuilder and open it again there is no exception anymore when viewing the jar analysis report. Can you confirm this?

**Comment by rterp** [comment]
Yep, looks like its working after closing and reopening Scene Builder.  Thanks for looking into it.
