### ISSUE TITLE
FlatSkin: NullPointerException changing the skin at runtime.

### ISSUE THREAD

**Issue by claudio-rosati** [HanSolo/Medusa#61]
```
java.lang.NullPointerException
	at eu.hansolo.medusa.skins.FlatSkin.resize(FlatSkin.java:239)
	at eu.hansolo.medusa.skins.FlatSkin.handleEvents(FlatSkin.java:167)
	at eu.hansolo.medusa.skins.FlatSkin.lambda$registerListeners$2(FlatSkin.java:152)
	at eu.hansolo.medusa.Gauge.fireUpdateEvent(Gauge.java:5502)
	at eu.hansolo.medusa.Gauge.setSkinType(Gauge.java:5491)
	at org.csstudio.display.builder.representation.javafx.widgets.GaugeRepresentation.updateChanges(GaugeRepresentation.java:69)
	at org.csstudio.display.builder.representation.RepresentationUpdateThrottle.lambda$0(RepresentationUpdateThrottle.java:200)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

**Comment by HanSolo** [comment]
fixed with last commit
