### ISSUE TITLE
NullPointerException passing from Gauge.SkinType.SIMPLE_SECTION to Gauge.SkinType.GAUGE

### ISSUE THREAD

**Issue by claudio-rosati** [HanSolo/Medusa#62]
When I start my test with a Gauge.SkinType.GAUGE skin I have the following:

![1](https://cloud.githubusercontent.com/assets/10833922/22372816/202cc928-e49f-11e6-8f40-bc287fa8e8ac.png)

Now I try to start with a Gauge.SkinType.SIMPLE_SECTION skin an after 5 seconds change it to Gauge.SkinType.GAUGE:

![2](https://cloud.githubusercontent.com/assets/10833922/22372818/202f0562-e49f-11e6-92db-a6dd7a1fad83.png)

After 5 seconds:

![3](https://cloud.githubusercontent.com/assets/10833922/22372817/202e2f34-e49f-11e6-9f38-a9bdb9839ce7.png)

After resizing the window:

![4](https://cloud.githubusercontent.com/assets/10833922/22372819/203b8558-e49f-11e6-8164-a5b0c23bed15.png)

and a series of NullPointerException are emitted in console:

```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at eu.hansolo.medusa.skins.SimpleSectionSkin.resize(SimpleSectionSkin.java:260)
	at eu.hansolo.medusa.skins.SimpleSectionSkin.handleEvents(SimpleSectionSkin.java:159)
	at eu.hansolo.medusa.skins.SimpleSectionSkin.lambda$registerListeners$0(SimpleSectionSkin.java:135)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:349)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyDoublePropertyBase.fireValueChangedEvent(ReadOnlyDoublePropertyBase.java:72)
	at javafx.beans.property.ReadOnlyDoubleWrapper.fireValueChangedEvent(ReadOnlyDoubleWrapper.java:103)
	at javafx.beans.property.DoublePropertyBase.markInvalid(DoublePropertyBase.java:113)
	at javafx.beans.property.DoublePropertyBase.set(DoublePropertyBase.java:147)
	at javafx.scene.layout.Region.setWidth(Region.java:858)
	at javafx.scene.layout.Region.resize(Region.java:1364)
	at javafx.scene.layout.Region.layoutInArea(Region.java:2325)
	at javafx.scene.layout.Region.layoutInArea(Region.java:2238)
	at javafx.scene.layout.Region.layoutInArea(Region.java:2179)
	at javafx.scene.layout.StackPane.layoutChildren(StackPane.java:342)
	at javafx.scene.Parent.layout(Parent.java:1087)
	at javafx.scene.Scene.doLayoutPass(Scene.java:552)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.PaintCollector.liveRepaintRenderJob(PaintCollector.java:320)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$ViewEventNotification.run(GlassViewEventHandler.java:831)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$ViewEventNotification.run(GlassViewEventHandler.java:792)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleViewEvent$368(GlassViewEventHandler.java:871)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleViewEvent(GlassViewEventHandler.java:870)
	at com.sun.glass.ui.View.handleViewEvent(View.java:539)
	at com.sun.glass.ui.View.notifyResize(View.java:875)
```

Here the test code:

```java
package se.ess.medusa.tests.gauge;


import eu.hansolo.medusa.Gauge;
import eu.hansolo.medusa.GaugeBuilder;
import eu.hansolo.medusa.Section;
import javafx.animation.AnimationTimer;
import javafx.application.Application;
import javafx.geometry.Insets;
import javafx.geometry.NodeOrientation;
import javafx.scene.Scene;
import javafx.scene.layout.StackPane;
import javafx.scene.paint.Color;
import javafx.stage.Stage;

import static javafx.application.Application.launch;


public class MainApp extends Application {

    public static void main( String[] args ) {
        launch(args);
    }

    private Gauge gauge;
    private long lastTimerCall;
    private AnimationTimer timer;

    @Override
    public void init() throws Exception {

        Gauge.SkinType skin = Gauge.SkinType.SIMPLE_SECTION;

        gauge = GaugeBuilder.create()
                            .skinType(skin)
                            .animated(true)
                            .title(skin.name())
                            .titleColor(Color.GREEN)
                            .minValue(0)
                            .maxValue(100)
                            .value(100)
                            .areas(new Section(-20, 0, Color.GREEN),
                                   new Section(0, 25, Color.ORANGE),
                                   new Section(25, 50, Color.MAGENTA))
                            .areasVisible(true)
                            .highlightAreas(true)
                            .sections(new Section(-20, 0, Color.BLUE),
                                      new Section(0, 25, Color.YELLOW),
                                      new Section(25, 50, Color.RED))
                            .sectionsVisible(true)
                            .highlightSections(true)
                            .build();

        lastTimerCall = System.nanoTime();
        timer = new AnimationTimer() {
            @Override
            public void handle( long now ) {
                if ( now > lastTimerCall + 5_000_000_000L ) {

                    gauge.setSkinType(Gauge.SkinType.GAUGE);
                    timer.stop();

                    lastTimerCall = now;

                }
            }
        };

    }

    @Override
    public void start( Stage stage ) throws Exception {

        StackPane pane = new StackPane(gauge);

        pane.setPadding(new Insets(20));
        pane.setNodeOrientation(NodeOrientation.LEFT_TO_RIGHT);

        Scene scene = new Scene(pane);

        stage.setTitle("Medusa Gauge Test");
        stage.setScene(scene);
        stage.show();

        timer.start();

    }

}
```

**Comment by HanSolo** [comment]
fixed with latest commit
